[deps]
ActiveInference = "688b0e7a-0122-4325-8669-5ff08899a59e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
